# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy.rb"
class Eocctl < Formula
  desc "Official EOC CLI tool."
  homepage "https://github.com/radiantlogic-v8/eocctl"
  version "0.1.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/radiantlogic-v8/eocctl/releases/download/v0.1.1/eocctl_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "dc13e3cdc797074f464add70b0ac714f3d6f0f38b5cd841f6029f86a741dbef1"

    def install
      bin.install "eocctl"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/radiantlogic-v8/eocctl/releases/download/v0.1.1/eocctl_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "5dd8e8cb83350ed195c939f4ca58d1d5733586a264a27971a1a92ed696511375"

    def install
      bin.install "eocctl"
    end
  end
end
